run_name: root_tcn_v1_train10
seed: 123
device: auto
data_dir: auto
output_dir: outputs

input_config:
  use_x3d_sam_rel: true
  use_x2d_img: true
  use_x2d_box: false #outliers à cause des bboxs
  use_bbox_feat: true
  bbox_clean_or_noisy: clean
  use_cam_feat: true
  cam_feat_type: boosted_clean
  use_ground_intersection: true
  use_valid_joints_as_input: true

dataset:
  max_sequences: null
  max_windows_per_sequence: null
  window_size: 81
  stride: 20
  min_valid_ratio: 0.5 # Minimum ratio of valid frames in a window to be included in training. Adjust as needed.
  pad_mode: edge #comment gérer les extrémités de la window (extrémité gauche pour le début, 1ères frames et extrémité droite pour la fin, dernières frames).
    #edge : on étire le bord : [0, 1, 2, 3, 4]->[3, 4, 4, 4, 4]
    #zero : on remplit le bord de vecteur null : [0, 1, 2, 3, 4]->[0, 0, 0, 1, 2]
    #reflect : on reflècte la séquence : [0, 1, 2, 3, 4]->[2, 1, 0, 1, 2] (pas réaliste pour du mouvement human)
    #none : pas de padding du tout (on perd des données)
  min_in_image_joints_ratio: 1
  # Filter out degenerate tiny boxes (pixels). Adjust as needed.
  min_bbox_width_px: 10
  min_bbox_height_px: 10
  # Reject bboxes too close to image borders (pixels), e.g. 10 or 20.
  min_bbox_margin_px: 10

model: #entree du tcn : [batch = 64, seq_len = 81, temporal_hidden_dim = 256]
  encoder_hidden_dims: [256, 256]
  temporal_hidden_dim: 256
  temporal_dilations: [1, 2, 4, 8] #chacun des 4 blocs a une dilatation différente, exemple avec dilation=2 : x[t-2], x[t], x[t+2]
  temporal_kernel_size: 3
  activation: gelu
  dropout: 0.1 #supp des neurones aléatoirement pendant l'entraînement pour éviter l'overfitting
  head_hidden_dims: [128]

optimizer:
  lr: 1.0e-3
  weight_decay: 1.0e-4 #penalisation, (adam w : le weight decay est en dehors de l'optimisateur, contrairement à adam classique) pour éviter les poids trop grands et favoriser la généralisation.

training:
  batch_size: 64
  epochs: 40
  num_workers: 2
  group_batches_by_sequence: true
  grad_clip_norm: 1.0
  early_stopping_patience: 10

loss_weights:
  root: 1.0
  root_axis_weights: [1.0, 1.0, 1.8] # x, y, z; increase z to emphasize depth.
  root_vel: 0.2
  root_acc: 0.0
  cam3d: 0.0
  proj: 0.0

eval:
  splits: [valid, test]
  batch_size: 64
  num_workers: 2
  save_predictions_npz: true
  save_predictions_csv: true
  aggregate_overlaps: mean

plots:
  enabled: true
  split_for_plots: valid
  seq_name: null
  person_idx: null
  num_frames_overlay: 6
  show_sam2d_overlay: false
  num_players_per_subplot: null

diagnostic_plots:
  enabled: true
  split_for_plots: valid
  root_error_vs_camera_distance: true
  root_error_vs_image_center_distance: true
  root_error_vs_player_speed: true
  speed_window: 5
